<?php require_once('template/header.phtml') ?>

<div class="row">
    <div class="slider_center slider_panel">
        <!--Slider of images-->
        <div class="row">
            <div id="demo" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ul class="carousel-indicators">
                    <li data-target="#demo" data-slide-to="0" class="active"></li>
                    <li data-target="#demo" data-slide-to="1"></li>
                    <li data-target="#demo" data-slide-to="2"></li>
                </ul>

                <!-- The slideshow -->
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="img-fluid sliderImage 1" src="images/HackCampHomePage3.jpeg" alt="slider 1st image ">
                    </div>
                    <div class="carousel-item">
                        <img class="img-fluid sliderImage 2" src="images/HackCampHomePage4.jpeg" alt="slider 2nd image ">
                    </div>
                    <div class="carousel-item">
                        <img class="img-fluid sliderImage 2" src="images/HackcampTeamwork2x.jpg" alt="slider 3rd image ">
                    </div>
                </div>

                <!-- Left and right controls -->

                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>

            </div>
        </div>
    </div>
</div>

<div class="row mt-5">
    <div class="col-md-6 col-lg-5 col-xl-4 p-0">
        <img src="images/member info.png" alt="..."  class="w-100">
    </div>
    <div class="col-md-6 col-lg-7 col-xl-8 text-center d-flex align-self-center">
        <h4 class="mx-auto">As an administrator you can view you each of your <br> team members progress of the tasks you have assigned them!</h4>
    </div>
</div>

<div class="row mt-5">
    <div class="col-md-5 col-lg-7 col-xl-8 text-center d-flex align-self-center">
        <h4 class="mx-auto">Your team tasks can be  beautifully organised in  <br>separate folders<br> </h4>
    </div>

    <div class="col-md-7 col-lg-5 col-xl-4 p-0">
        <img src="images/Home Page Task Wireframe@2x.jpg" alt="..." class="w-100">
    </div>
</div>



<?php require_once('template/footer.phtml') ?>
