<?php require_once ("Views/template/header.phtml");?>
    <div class="row justify-content-center min-vh-100 border-danger d-flex" style="background-color: rgba(0, 0, 0, 0.1)">
        <div class="col-sm-10 col-md-8 col-lg-7 p-0 align-self-center">
            <!--        Card to display the details of the task -->
            <div class="card border-dark p-3 shadow-lg mh-100">
                <div class="card-header bg-light border-bottom border-dark">

                    <!--                Delete button -->
                    <button class="fas fa-trash-alt btn-outline-danger btn-lg border border-danger" data-toggle="modal" data-target="#deleteProjectModal"></button>
                </div>
                <div class="card-body">
                    <div class="mt-5">

                    </div>
                    <div class="mt-5">
                        <h3 class="card-title text-center"><?php echo $view->projectName;?></h3>
                    </div>
                    <div class="mt-5">
                        <a href="<?php echo 'search.php?projectID='.$view->projectID;?><?php if(isset($_GET['teamID'])) : ?>&teamID=<?php echo $_GET['teamID']; ?><?php endif;?>" class="btn btn-outline-dark btn-block shadow-none border rounded-pill">View all tasks</a>
                    </div>
                    <div class="mt-5">
                        <button class="btn btn-outline-dark btn-block shadow-none border rounded-pill" data-toggle="modal" data-target="#addTaskModal">ADD TASK</button>
                    </div>
                </div>
            </div>
        </div>

        <!--                    modal for the add task form -->
        <div id="addTaskModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title">Add a Task</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <!--                        Add Task Form -->
                        <form method="post" action="<?php echo 'project.php?projectID='.$view->projectID;?>">
                            <div class="form-group">
                                <label for="taskName">Task Name</label>
                                <input type="text" name="taskName" class="form-control" placeholder="e.g Read Biology" required>
                            </div>
                            <div class="form-group">
                                <label for="startDate">Task Start Date</label>
                                <input type="date" name="startDate" class="form-control" placeholder="YYYY-MM-DD" required>
                            </div>
                            <div class="form-group">
                                <label for="endDate">Task End Date</label>
                                <input type="date" name="endDate" class="form-control" placeholder="YYYY-MM-DD" required>
                            </div>
                            <div class="form-group">
                                <label for="comments">Comments</label>
                                <textarea type="text" name="comments" class="form-control" placeholder="Comment on this task..." required></textarea>
                            </div>
                            <div class="form-group">
                                <label for="effort">Effort</label>
                                <input type="number" name="effort" class="form-control" placeholder="The amount of time you want to work on this task today" required></input>
                            </div>
                            <div class="form-group">
                                <input class="btn btn-outline-dark form-control" type="submit" name="taskSubmitBtn" value="Add">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>

        <!--    Modal for delete project-->
        <div id="deleteProjectModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Delete Project</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <!--                        Confirmation form -->
                        <form method="post">
                            <div class="form-group">
                                <p class="text-center">Are you sure you want to delete this project?</p>
                            </div>
                            <div class="form-group text-center">
                                <input class="btn btn-outline-danger" type="submit" name="delProjectSubmitBtn" value="Yes, Delete">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php require_once ("Views/template/footer.phtml");?>
