    </div>

<!---->
<!--    <div class="container-fluid bg-dark text-white text-center" style="margin-top: 2vh; min-height: 100%; padding: .8rem;">-->
<!--        <div id="footer" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">-->
<!--            <p>Web-site development using the MVC design pattern and the Bootstrap CSS framework</p>-->
<!--        </div>-->
<!--    </div>-->

    <!--    <img class="card-img" src="images/HackCamp Footer.png" alt="Card image" style="opacity: 0.6; max-height: 20vh">-->
    <!--    <div class="card-img-overlay">-->
    <div class="card-body text-white mt-5" style="background-color: #3B4621">
        <img class="float-right" src="images/logo4.png" alt="Card image" style="opacity: 0.6; max-height: 10vh; max-width: 10vh">
        <h4 class="card-title">Head Office</h4>
        <h5 class="card-text">University Of Salford, <br>Manchester, <br> United Kingdom</h5>

        <!--    </div class="card-img-overlay">-->
    </div>
    <div class="card-footer">
        <p class="card-text">Web-site development using the MVC design pattern and the Bootstrap CSS framework</p>
        <p class="card-text">Last updated 3 mins ago</p>
    </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!--    Created Javascript -->
    <script src="js/main.js"></script>

    </body>
    </html>

    <!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<!--    Created Javascript -->
    <script src="js/main.js"></script>
    </body>
</html>